### ISSUE TITLE
Enlace a un curso y videos sobre Angular JS en español - DesarrolloWeb

### ISSUE THREAD

**Issue by desaextremo** [alejo8591/unipiloto-am-2#1]
http://www.desarrolloweb.com/manuales/manual-angularjs.html
https://www.youtube.com/watch?v=a7XOVa5rybg
https://www.youtube.com/watch?v=9kk1A5_IaQ0
https://www.youtube.com/watch?v=M78gCRhqeUA

**Comment by desaextremo** [comment]
https://drive.google.com/file/d/0By20oENHm0_ZdTZldFoyeGZTVzQ/view?usp=sharing

**Comment by alejo8591** [comment]
@desaextremo Listo publicada la información pero el anuncio lo hare la próxima semana, cuando trabajemos el tema de Node.JS

Se cierra el issue.

**Comment by JhonCastilloH** [comment]
Angular Resources

Angularjs.org - Official AngularJS Documentation
Egghead.io - Bite-sized web development training.
Thinkster.io - Learn to Build Modern Web Apps.
Meetup - Find a Local Angular Meetup.
Dash - Instant offline access to +130 API Docs!

**Comment by alejo8591** [comment]
@JhonCastilloH Muchas gracias los publicare y en el proximo correo lo hare publico y en clase también.
