### ISSUE TITLE
NODEJS - Modulos Instalados 

### ISSUE THREAD

**Issue by jorgeordovi** [alejo8591/unipiloto-am-2#10]
Tengo problemas para ubicar cuales fueron los modulos que instalamos en NODEJS hasta la fecha. podrian indicar?

Gracias!

**Comment by desaextremo** [comment]
Buenos dias:

Me parece que el archivo package.json te muestra las dependencias

{
  "name": "25042015_2",
  "version": "1.0.0",
  "description": "prueba",
  "main": "gulpfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "covalle",
  "license": "bsd",
  "dependencies": {
    <strong>
    "body-parser": "^1.12.3",
    "consolidate": "^0.12.1",
    "debug": "^2.1.3",
    "express": "^4.12.3",
    "fs": "0.0.2",
    "swig": "^1.4.2"
    </strong>
  }
}

en este caso creo que los paquetes usados son:

<ul>
<li>body-parser</li>
<li>consolidate</li>
<li>debug:</li>
<li>express</li>
<li>fs</li>
<li>swig</li>
</ul>

y para la descarga ubicados en la consola de node usamos el comando 
npm install <nombre del modulo> --save (iniciando con express).

**Comment by alejo8591** [comment]
@jorgeordovi recuerda que para eso utilizamos el `package.json`que es el archivo que contiene la información de la aplicación en este caso el JSON

**Comment by alejo8591** [comment]
@jorgeordovi recuerda que para eso utilizamos el `package.json`que es el archivo que contiene la información de la aplicación en este caso el JSON que nos muestra @desaextremo: 

``` json
{
"name": "25042015_2",
"version": "1.0.0",
"description": "prueba",
"main": "gulpfile.js",
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
"author": "covalle",
"license": "bsd",
"dependencies": {
"body-parser": "^1.12.3",
"consolidate": "^0.12.1",
"debug": "^2.1.3",
"express": "^4.12.3",
"fs": "0.0.2",
"swig": "^1.4.2"
}
}
```

Si es la primera vez y no esta presente en la carpeta, lo debemos crear con `npm init`; en adelante las instrucciones que nos pide como nombre, versión, licencia, descripción entre otros...

Después de esto si realizas lo que te indica @desaextremo agregar los paquetes que hacen falta:
- body-parser (Parser de información que viaja a través de tramas HTTP)
- consolidate (Motor de templates para ExpressJS)
- debug (Herramienta para seguimiento y mensaje de errores)
- express (Framework MVC escrito en JavaScript y que nos ayuda con tareas básicas de desarrollo)
- fs (Modulo para interactuar con archivos, en este caso abrimos y sacamos el JSON contenido)
- swig (Lenguaje de templates para los HTML de ExpressJS)

Los instalas con el comando `npm install nombre_paquete --save` para que los agregue al objeto `dependencies` en el `package.json` que es donde se gestionan las dependencias del proyecto. Después cuando lo vuelvas a utilizar, y este almacenada información como:

``` json
{
"dependencies": {
"body-parser": "^1.12.3",
"consolidate": "^0.12.1",
"debug": "^2.1.3",
"express": "^4.12.3",
"fs": "0.0.2",
"swig": "^1.4.2"
}
}
```

simplemente instalas todo con `npm install`

**Comment by jorgeordovi** [comment]
Mil gracias  @desaextremo y @alejo8591 ahora esta todo en orden.
