### ISSUE TITLE
problema de complicación android 

### ISSUE THREAD

**Issue by ingjuanocampo** [alejo8591/unipiloto-am-2#11]
![captura](https://cloud.githubusercontent.com/assets/11579887/7550979/2527abc6-f63c-11e4-9b07-5bb82db20156.PNG)

**Comment by Maru27** [comment]
El numero de mi maquina D302-03

**Comment by 9ggomez** [comment]
D302-01 error en la maquina

**Comment by aspalenciap** [comment]
En la máquina D302-04 aparece el error "Please install Android target: "android-22" cuando se ejecuta la orden "cordova build android"

**Comment by alejo8591** [comment]
@9ggomez , @Maru27 , @aspalenciap la idea es que tomaran el `print screen` para saber el error que se presenta.

¿@9ggomez cómo sabemos cual es tu error?, ¿@Maru27 cual es problema en tu maquina?, chicos por favor un poco más especifico el problema la próxima vez ;)

**Comment by alejo8591** [comment]
Ya fue reportado a soporte técnico de las salas. Les estaré contando el estado de la incidencia. ¡Saludos!.

**Comment by Maru27** [comment]
Buenas noches profe, el error de mi maquina es  "Please install Android target: "android-22" cuando se ejecuta el comando "cordova build android"

**Comment by alejo8591** [comment]
@Maru27 Listo, entendido, de todos modos ya fue reportado. :+1:

**Comment by Maru27** [comment]
Muchas gracias!

**Comment by alejo8591** [comment]
@Maru27 , @9ggomez , @ingjuanocampo , @aspalenciap Se cierra al presente `issue` ya que no se reportaron novedades y todo trabajo bajo control.
