### ISSUE TITLE
Problema compilación android

### ISSUE THREAD

**Issue by jagarciar** [alejo8591/unipiloto-am-2#12]
![error](https://cloud.githubusercontent.com/assets/11579880/7551179/ba5b64aa-f644-11e4-8eb0-f4941ae27cd9.PNG)

**Comment by vitorresr** [comment]
Buenas tardes en el equipo D302-05 se presenta el mismo error.

**Comment by ricarsant** [comment]
D302-11 ERROR EN LA MAQUINA CON ANDROID-22:

[Error: Please install Android target: "android-22".

**Comment by LinaSep** [comment]
En el equipo D302-08 se presenta el mismo error, adjunto:

![error-construir-apk-android-equipo-d302-08](https://cloud.githubusercontent.com/assets/11579882/7551198/770d892a-f645-11e4-86a4-9037e5d5bb17.PNG)

**Comment by jagarciar** [comment]
Equipo D302-22

**Comment by JhonCastilloH** [comment]
![captura](https://cloud.githubusercontent.com/assets/11579892/7551237/63da5084-f647-11e4-9eba-f7c6094b099c.PNG)

**Comment by JhonCastilloH** [comment]
equipo d302-10
![captura](https://cloud.githubusercontent.com/assets/11579892/7551240/76f7d646-f647-11e4-94e4-4e4ae1988939.PNG)

**Comment by alejo8591** [comment]
Ya fue reportado a soporte técnico de las salas. Les estaré contando el estado de la incidencia. ¡Saludos!.

**Comment by alejo8591** [comment]
@JhonCastilloH , @vitorresr  , @ricarsant , @LinaSep Se cierra al presente `issue` ya que no se reportaron novedades y todo trabajo bajo control. @jagarciar [Queda abierta la incidencia registrada el día sábado por la novedad en tu desktop](http://git.io/vTZTN).
