### ISSUE TITLE
Problema en equipo D302-18 al ejecutar cordova emulate android

### ISSUE THREAD

**Issue by fannytg** [alejo8591/unipiloto-am-2#13]
Se presenta este mensaje de error en el equipo D302-18.  Diplomado apm
![cordova prepare error equipo d302-18](https://cloud.githubusercontent.com/assets/11580120/7551180/c974a7ee-f644-11e4-8ece-24ab9489d6a4.JPG)

**Comment by fannytg** [comment]
De antemano mil gracias por la gestión y ayuda.
Cordial saludo,
Fanny Angélica Torrado G.

**Comment by alejo8591** [comment]
Ya fue reportado a soporte técnico de las salas. Les estaré contando el estado de la incidencia. ¡Saludos!.

**Comment by alejo8591** [comment]
@fannytg Se cierra al presente `issue` ya que no se reportaron novedades y todo trabajo bajo control.
