### ISSUE TITLE
Problema al construir apk de android con phonegap - equipo D302-17

### ISSUE THREAD

**Issue by olmandocs** [alejo8591/unipiloto-am-2#14]
Al intentar generar el .apk para una aplicación en mi equipo no encuentra la versión 22 de android, mi equipo es el D302-17, muchas gracias 
![captura](https://cloud.githubusercontent.com/assets/10672341/7551196/5e981cf2-f645-11e4-8dcb-aef91d3ead17.PNG)

**Comment by alejo8591** [comment]
Ya fue reportado a soporte técnico de las salas. Te estaré contando el estado de la incidencia. ¡Saludos!.

**Comment by alejo8591** [comment]
@olmandocs Se cierra al presente `issue` ya que no se reportaron novedades y todo trabajo bajo control.
