### ISSUE TITLE
Guía Completa de CSS3

### ISSUE THREAD

**Issue by Maru27** [alejo8591/unipiloto-am-2#15]
Buenas noches profe,

En: wiki, material de apoyo, css, Guía Completa de CSS3, me sale la siguiente información: 

![image](https://cloud.githubusercontent.com/assets/11579888/7578780/b3b29fec-f81f-11e4-8612-bc5bac407c8b.png)

Debo de hacer algún tipo de procedimiento para ver la página?

**Comment by alejo8591** [comment]
@Maru27 Ya reviso el enlace, al parecer esta caído. ¡Pero!, ya te cuento.

**Comment by alejo8591** [comment]
@Maru27 Enlace actualizado, ¿por favor prueba y me cuentas?
