### ISSUE TITLE
problema cordova build android

### ISSUE THREAD

**Issue by ingjuanocampo** [alejo8591/unipiloto-am-2#16]
Saludos, 
estube revisando el tema de la compilacion android en mi equipo persona, al parecer todo funciona bien para una aplicacion basica. Sin embargo cuando intento compilar el ultimo laboratorio 
que tiene el plugin del acelerometro me sale lo siguiente: 
![image](https://cloud.githubusercontent.com/assets/11579887/7579823/551a127a-f82f-11e4-9d21-4d66c6b90410.png)

Si alguien lo resolvio o lo entiende les agradesco la ayuda. 

Bye

**Comment by alejo8591** [comment]
Prueba lo siguiente `npm install shelljs -g`

**Comment by ingjuanocampo** [comment]
Lo solucione incluyendo las siguientes dependecias, 
- npm install which --save
- npm install q --save
- npm install shelljs --save

No se por que la inclusion global no reconocia el shelljs 

Finalmente el proyecto me corrio en mi celular Android 5.0

**Comment by alejo8591** [comment]
@ingjuanocampo muchas gracias por compartir la solución
