### ISSUE TITLE
Problea con requerimiento D-302

### ISSUE THREAD

**Issue by reich88c** [alejo8591/unipiloto-am-2#17]
Buenos dias profe

**Comment by alejo8591** [comment]
@reich88c Hola Carlos buenos días, voy a documentar lo que me enviaste:

Error:
![captura](https://cloud.githubusercontent.com/assets/1151850/7611580/ee3a83ec-f94a-11e4-8863-258e26935928.png)

Configuración de las variables de entorno:

``` shell
JAVA_HOME: C:\Program Files\Java\jdk1.7.0_79

ANT_HOME: C:\apache-ant-1.9.4

PATH: C:\Users\Adminespec\AppData\Roaming\npm;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\Program Files (x86)\Android\android-sdk\tools
```

**Comment by alejo8591** [comment]
@reich88c revisando por favor instala los paquetes del `Android22`, eso demora un buen rato, me as contando, quedo atento.

**Comment by alejo8591** [comment]
@reich88c por favor revisa el equipo del docente porque al parecer la sesión con `adminespec` tiene problemas de permisos...

**Comment by alejo8591** [comment]
@reich88c Se cierra al presente `issue` ya que no se reportaron novedades y todo trabajo bajo control.
