### ISSUE TITLE
Problema compilación android D302-22

### ISSUE THREAD

**Issue by jagarciar** [alejo8591/unipiloto-am-2#18]
![error2](https://cloud.githubusercontent.com/assets/11579880/7664210/ac49ee2e-fb42-11e4-888e-01014a0e5614.PNG)

**Comment by alejo8591** [comment]
@jagarciar saludos, se reporta en la lista y a través de correo electrónico, te estaré contando novedades.

**Comment by alejo8591** [comment]
@jagarciar ya revisamos y volvimos a instalar mañana viernes por favor probar.
