### ISSUE TITLE
Drivers para alcatel con Firefox OS

### ISSUE THREAD

**Issue by JhonCastilloH** [alejo8591/unipiloto-am-2#19]
Este es el video de explicacion, para cuando el WebID no reconoce el dispositivo.

https://www.youtube.com/watch?v=t1t2LLZk4_g

https://drive.google.com/folderview?id=0B9v1uW_rsUNeWWR4UFhsX2U5MkE&usp=sharing

**Comment by alejo8591** [comment]
@JhonCastilloH Gracias por el aporte, ¡Genial!.
