### ISSUE TITLE
Chuletas o Cheat Sheet  de las tecnologias requeridas en clase

### ISSUE THREAD

**Issue by desaextremo** [alejo8591/unipiloto-am-2#2]
<strong>Cheat Sheet JQuery</strong>: https://drive.google.com/file/d/0By20oENHm0_Zd2NZTW9KMzJsUHc/view?usp=sharing

<strong>Cheat Sheet CSS Parte 1</strong>: https://drive.google.com/file/d/0By20oENHm0_ZUldMMVZpTm0wenM/view?usp=sharing

<strong>Cheat Sheet CSS 3</strong>: 
https://drive.google.com/file/d/0By20oENHm0_ZcHN6YjB3cENrcFU/view?usp=sharing

<strong>Cheat Sheet HTML Core</strong>: 
https://drive.google.com/file/d/0By20oENHm0_ZVWhwZmtXM0JIUnM/view?usp=sharing

<strong>Cheat Sheet HTML5</strong>: 
https://drive.google.com/file/d/0By20oENHm0_ZLVNhVHF6WjJNdFk/view?usp=sharing

<strong>Cheat Sheet NODE JS</strong>:
https://drive.google.com/file/d/0By20oENHm0_Zbjhncm9FLXJlZGM/view?usp=sharing 

<strong>Cheat Sheet HTML5 Canvas</strong>:
https://drive.google.com/file/d/0By20oENHm0_ZbFJvc1JodmhxR1k/view?usp=sharing

<strong>Cheat Sheet HTML5 Websockets</strong>:
https://drive.google.com/file/d/0By20oENHm0_ZWHZ2ZjFocFkyek0/view?usp=sharing

<strong>Cheat Sheet HTML5 Webworkers</strong>:
https://drive.google.com/file/d/0By20oENHm0_ZU09hbHplOXRRZjA/view?usp=sharing

<strong>Cheat Sheet HTML5 Mobile</strong>:
https://drive.google.com/file/d/0By20oENHm0_ZVHg0QkZvVm43Z2M/view?usp=sharing

<strong>Cheat Sheet Phonegap</strong>:
https://drive.google.com/file/d/0By20oENHm0_ZeUpMcHZlQ2RwTE0/view?usp=sharing

<strong>Cheat Sheet CSS3 Basics</strong>:
https://drive.google.com/file/d/0By20oENHm0_ZWVhIXzFiaGZYVlU/view?usp=sharing

<strong>Cheat Sheet Expresiones regulares</strong>:
https://drive.google.com/file/d/0By20oENHm0_ZaDNmc0YxZHNscEU/view?usp=sharing

<strong>Cheat Sheet HTML5 IndexedDB</strong>:
https://drive.google.com/file/d/0By20oENHm0_ZazhiNWR1bjlDNHM/view?usp=sharing

<strong>Cheat Sheet AngularJS</strong>:
https://drive.google.com/file/d/0By20oENHm0_ZX2w0bWN2czFrREU/view?usp=sharing

**Comment by alejo8591** [comment]
@desaextremo muchas gracias por el aporte, no dudes en seguir agregando y compartiendo. Queda publicado en la siguiente url: http://git.io/vvjdX 

Se cierra el issue.
