### ISSUE TITLE
problema con el plugin orientation en firefoxos

### ISSUE THREAD

**Issue by ricarsant** [alejo8591/unipiloto-am-2#20]
Saludos 
La emulación  en firefox me funciono instalando el plugin con este comando:
`cordova plugin add org.apache.cordova.device-orientation`

**Comment by alejo8591** [comment]
Este problema se presentaba cuando preparaban para la plataforma `Firefox OS` y la App al parecer se quedaba bloqueada. Para los que se les presenta esta es la solución para que la prueben. Gracias @ricarsant por la información y la colaboración.
