### ISSUE TITLE
Firefoxos - Inconveniente con el plugin de geolocalizacion: org.apache.cordova.geolocation

### ISSUE THREAD

**Issue by desaextremo** [alejo8591/unipiloto-am-2#21]
En la plataforma FirefoxOs se presenta un error al intentar hacer uso del plugin de geolocalización:

<strong>org.apache.cordova.geolocation</strong>

Por primera vez

<strong>
Geolocalization Error#1
User denied geolocation
prompt
</strong>
El inconveniente se soluciona modificando el archivo manifest.webapp con las lineas:

<pre>
"permissions": {
    "geolocation": { "description": "Used to position the map to your current position" }
    }
</pre>

El archivo modificado quedar&iacute;a as&iacute;

<pre>
{
    "launch_path": "/index.html",
    "installs_allowed_from": [
        "*"
    ],
    "version": "0.0.1",
    "name": "geo",
    "description": "A sample Apache Cordova application that responds to the deviceready event.",
    "developer": {
        "name": "Apache Cordova Team",
        "url": "http://cordova.io"
    },
    "icons": {},
    "permissions": {
    "geolocation": { "description": "Used to position the map to your current position" }
    }
}
</pre>

**Comment by fannytg** [comment]
Gracias por el aporte

**Comment by olmandocs** [comment]
buen aporte muchas gracias

**Comment by alejo8591** [comment]
@desaextremo Muchas gracias muy buen aporte.
