### ISSUE TITLE
"ADB Server Didn't ACK" // failed to start daemon PC: D302-12

### ISSUE THREAD

**Issue by andresDesigner** [alejo8591/unipiloto-am-2#22]
![image](https://cloud.githubusercontent.com/assets/11579885/7784643/c60970b4-0132-11e5-8fe1-0632ef105c12.png)

Link con ayuda para tratar de resolver el problema:
http://stackoverflow.com/questions/15136252/android-adb-didnt-ack-issue-in-eclipse

**Comment by andresDesigner** [comment]
Continuando con la solución al error encontré que parte del caso se resuelve actualizando a través del SDK MANAGER los módulos:
![image](https://cloud.githubusercontent.com/assets/11579885/7895234/e8bc040a-0646-11e5-876f-55fccad3596f.png)

Una vez actualizados, se debe abrir el Admin. de Tareas de windows y finalizar el proceso adb.exe, que con este error se ejecuta 2 veces cada vez que se consulta el Bind en consola cordova
![image](https://cloud.githubusercontent.com/assets/11579885/7895240/1685a710-0647-11e5-9a2c-d2605410ac59.png)

Luego, se ingresa a la carpeta Android\android-sdk\platform-tools y se ejecuta la consola el comando 
![image](https://cloud.githubusercontent.com/assets/11579885/7895244/646f5b74-0647-11e5-846b-292cde27719b.png)

![image](https://cloud.githubusercontent.com/assets/11579885/7895246/7543de70-0647-11e5-9a09-a9d3bdd997b0.png)

Y finalmente el comando adb-start server.

Al correr el adb devices en consola cordova se ejecuta correctamente pero no muestra los equipos:

![image](https://cloud.githubusercontent.com/assets/11579885/7895259/099d0510-0648-11e5-8efc-9a20ba3bcf86.png)

Eso soluciona el error del daemon pero deja abierto a que la configuración del genymotion se debe arreglar en:
![image](https://cloud.githubusercontent.com/assets/11579885/7895250/a9aaf98c-0647-11e5-856c-4dade31ca4ee.png)

Seleccionando manualmente el modulo android SDK de la ruta donde este instalado en el equipo, reiniciando los servicios en las diferentes páginas que consulté dice que debería funcionar.

El error persiste porque el SDK no logra actualizarse desde el manager correctamente. Hace falta hacer la prueba de desinstalar del todo y volver a instalarlo.

Fuentes:
https://wiki.appcelerator.org/display/guides2/Installing+Genymotion#InstallingGenymotion-Failedtostartdaemon

https://github.com/NativeScript/nativescript-cli/issues/167

**Comment by alejo8591** [comment]
Se reinstalo de nuevo el `SDK Manager` por favor probar de nuevo.

**Comment by andresDesigner** [comment]
No sirve aún...sugiero destruir la maquina.
![image](https://cloud.githubusercontent.com/assets/11579885/8142402/1b7cc58c-1141-11e5-891f-1c4423755712.png)

**Comment by alejo8591** [comment]
@andresDesigner ya quedo la orden de destrucción total

![image](http://media.tumblr.com/tumblr_ltl4rtVGZ61qghvhf.jpg)
