### ISSUE TITLE
Error adb devices "ADB server didn't ACK" Equipo D302-04

### ISSUE THREAD

**Issue by aspalenciap** [alejo8591/unipiloto-am-2#24]
![image](https://cloud.githubusercontent.com/assets/11579896/7784665/81569f36-0133-11e5-80a3-c532e2621990.png)

![image](https://cloud.githubusercontent.com/assets/11579896/7784673/c727c7ba-0133-11e5-9ee5-969e325cd90a.png)

**Comment by alejo8591** [comment]
Se reinstalo de nuevo el `SDK Manager` por favor probar de nuevo.
