### ISSUE TITLE
Firefox OS - Inconveniente con los permisos del plugin de contactos "Contacts" 

### ISSUE THREAD

**Issue by olmandocs** [alejo8591/unipiloto-am-2#25]
Buenas tardes, al igual que lo reportó esta mañana nuestro compañero @desaextremo, al intentar hacer uso de otro plugin de cordova (cordova-plugins-contacts) se presenta el siguiente error:

![image](https://cloud.githubusercontent.com/assets/10672341/7785939/2a95fd92-0172-11e5-8db4-b6f36bb98eb1.png)

Para solucionarlo en el archivo manifest.webapp que se genera en el www de la plataforma Firefox OS se deben agregar las siguientes lineas de código: 

```
    "type": "privileged",
    "permissions": {
        "contacts": {
            "access": "readwrite",
            "description": "Describe why there is a need for such permission"
        }
    }
```

Con lo que el archivo modificado sería mas o menos el siguiente:

```
{
    "launch_path": "/index.html",
    "installs_allowed_from": [
        "*"
    ],
    "version": "0.0.1",
    "name": "lab46",
    "description": "A sample Apache Cordova application that responds to the deviceready event.",
    "developer": {
        "name": "Apache Cordova Team",
        "url": "http://cordova.io"
    },
    "icons": {},
    "type": "privileged",
    "permissions": {
        "contacts": {
            "access": "readwrite",
            "description": "Describe why there is a need for such permission"
        }
    }
}
```

Es importante agregar esto después de hacer el "prepare" para la plataforma y se debe agregar siempre, ya que al ejecutar el comando cordova prepare firefoxos el archivo manifest.webapp se sobre escribe.

Saludos.

**Comment by alejo8591** [comment]
@olmandocs muchas gracias, excelente aporte!
