### ISSUE TITLE
Error EO

### ISSUE THREAD

**Issue by jagarciar** [alejo8591/unipiloto-am-2#26]
![eonent](https://cloud.githubusercontent.com/assets/11579880/7904518/7c1e1020-07c4-11e5-95b9-88aa0049b6d5.JPG)

Después de tener instalado node js, cordova e ionic y bajo las siguientes variables de entorno se genera el siguiente error (ejecutando la consola como usuario y como administrador) al adicionar una plataforma sobre un proyecto.

ANDROID_HOME = C:\Users\J Garcia\AppData\Local\Android\sdk1;
ANT_HOME = C:\Program Files\Java\apache-ant-1.9.4;
JAVA_HOME = C:\Program Files\Java\jdk1.7.0_51;
PATH = C:\ProgramData\Oracle\Java\javapath;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\app\jagarcia\product\12.1.0\dbhome_1\bin;C:\Program Files (x86)\MIT\Kerberos\bin;C:\Program Files\Java\jdk1.7.0_51\bin;C:\Program Files\Java\apache-ant-1.9.4\bin; C:\Users\J Garcia\AppData\Local\Android\sdk1\tools C:\Users\J Garcia\AppData\Local\Android\sdk1\platform-tools;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\

**Comment by alejo8591** [comment]
@jagarciar Antes de abrir la consola por favor en cuenta las siguientes indicaciones:

> para tener en cuenta: Mientras que la opción Ejecutar como administrador está disponible al hacer clic en un acceso directo al programa en el escritorio, la misma opción no aparece al hacer clic en acceso directo al programa en la pantalla de inicio.

Entonces para ejecutar `Node.js command prompt` con derechos de administrador en Windows 8 podría ser:
- Cambiar a la pantalla de inicio de Windows 8 y escribes `Node.js command prompt` para ver el programa en la lista de aplicaciones.
- Clic en `Node.js command prompt` para poder ver la opción avanzada.
- Clic en `Avanzadas` y seleccionamos la opción `Ejecutar como Administrador`.

**Comment by alejo8591** [comment]
¿@jagarciar el error fue resuelto o continuamos con el `issue` abierto?
