### ISSUE TITLE
Material de apoyo para el uso de $resource

### ISSUE THREAD

**Issue by cmauroie** [alejo8591/unipiloto-am-2#27]
El siguiente link 
http://www.sitepoint.com/creating-crud-app-minutes-angulars-resource/
sirve como ayuda para implementar:
- Servicio con: $resource. "backend"
- App para interactuar con el servicio creado REST API.

En mi caso he implementado solo la App. y utilice el servicio de la página:
http://movieapp-sitepointdemos.rhcloud.com/

**Comment by alejo8591** [comment]
@cmauroie gracias por el excelente aporte, lo estaré publicando la siguiente semana que tocaremos estos temas este fin de semana.
