### ISSUE TITLE
Error al construir el apk para android desde la consola

### ISSUE THREAD

**Issue by aspalenciap** [alejo8591/unipiloto-am-2#28]
![image](https://cloud.githubusercontent.com/assets/11579896/8028734/03113e36-0d79-11e5-87a3-eee7b7e16af2.png)

¿Cómo puedo corregir este error?

Para firefoxos y para browser no se presenta ningún problema.

Sin embargo, abriendo el proyecto desde android studio y modificando la línea 26 (borrando href="#") de los archivos config.xlm que están en C:...\proyecto_1\ProductApp\platforms\android\build\intermediates\res\debug
C:...\proyecto_1\ProductApp\platforms\android\res\xml
pude crear al apk para android e instalarlo en mi dispositivo.

//////

en el index.html que está en www he escrito esto en el ion-content

```
      <div class="list list-inset">
          <label class="item item-input">
              <input type="text" placeholder="Correo electrónico">
          </label>
          <label class="item item-input">
              <input type="password" placeholder="Contraseña">
          </label>
      </div>
      <div class="col text-center">
        <button class="button button-full button-balanced" >
          Ingresar
        </button>
        <br />
        <br />
        <button class="button button-full button-stable" >
          Olvide mi contraseña
        </button>
        <button class="button button-full button-positive" >
          Registrarse
        </button>
        <button class="button button-full button-stable" >
          ¿Cómo funciona esta aplicación?
        </button>
      </div>
```

Se obtiene esto:
![image](https://cloud.githubusercontent.com/assets/11579896/8028855/ce95fa64-0d7a-11e5-916b-13e066202c54.png)

**Comment by alejo8591** [comment]
@aspalenciap en tu directorio de trabajo o del usuario del sistema operativo, se crea una carpeta llamada `Android` por favor elimina y vuelve a agregar la plataforma: `ionic platform add android`.
