### ISSUE TITLE
Como puedo leer Json con Ajax?

### ISSUE THREAD

**Issue by cmauroie** [alejo8591/unipiloto-am-2#29]
Estoy haciendo lectura de un Json, pero en mi caso tiene una estructura diferente y la información que encuentro es igual al ejemplo de clases de Ajax: el cual replique en un ejemplo con ionic.
"www/js/data.json"

[
    {
    "Name" : "Mahesh Parashar",
    "RollNo" : 101,
    "Percentage" : "80%"
    },
    {
    "Name" : "Dinkar Kad",
    "RollNo" : 201,
    "Percentage" : "70%"
    },
    {
    "Name" : "Robert",
    "RollNo" : 191,
    "Percentage" : "75%"
    },
    {
    "Name" : "Julian Joe",
    "RollNo" : 111,
    "Percentage" : "77%"
    }
]
Hasta aquí todo funciona bien pero cuando quiero leer el siguiente json: "www/js/datajson2.json"

{
    "profile": {
        "id": 270,
        "name": "Carlos Villegas",
        "username": "gole",
        "email": "gole@hotmail.com"}
    }

no consigo visualizarlo en el index.html, espero que alguien me pueda colaborar con esta duda. 
Anexo el repositorio que utilizo, construido en ionic listo para usar. 

https://github.com/cmauroie/App_ajax

**Comment by alejo8591** [comment]
Tienes lo siguiente en el `index.html`:

``` html

<div ng-controller="studentController_profile">
          <h4>Id Json 2</h4>
  <a ng-repeat="profile in profiles"> {{ profile.id}} </a> 

```

prueba con lo siguiente:

``` html

<div ng-controller="studentController_profile">
          <h4>Id Json 2</h4>
  <a ng-repeat="(key, value) in profiles"> {{ key }} : {{ value }} </a> 

```

**Comment by cmauroie** [comment]
Funciona :+1: 
Gracias Alejandro.
