### ISSUE TITLE
Como integrar Plugin Cordova 2.1 en Xcode 6.3

### ISSUE THREAD

**Issue by cmauroie** [alejo8591/unipiloto-am-2#3]
Esta duda se presento cuando quise utilizar el plugin BarcodeScanner de Cordova 2.1 en Xcode para una app IOS, consigo el funcionamiento con las versiones 2.5 y 3.0 de cordova, pero el proyecto principal corre con Cordova 2.1 motivo por el cual estoy haciendo el desarrollo para esta versión, entonces quisiera saber como hacer la integración de los plugin para IOS ya que cambia mucho con relación a Android. y si tengo algún inconveniente con relación a las versiones de Cordova y Xcode.

**Comment by alejo8591** [comment]
@cmauroie por favor detalla como realizas el proceso y como son las pruebas que realizas, documenta con imágenes y el paso a paso de tu proceso, que herramientas utilizas y con que versiones; todo en detalle para poder ayudarte de la mejor y la manera más acertada. ¡Gracias!
