### ISSUE TITLE
Informacion De Contactos Para El Futuro

### ISSUE THREAD

**Issue by JhonCastilloH** [alejo8591/unipiloto-am-2#30]
Porfavor, ingresar sus datos a la lista para, mantenernos en contacto y asi poder seguir trabajando y aprendiendo

Nombre : Jhon Castillo
Cel: 3164408400
Tel: 3142826081
mail:profe.johncastillo@gmail.com

**Comment by andresDesigner** [comment]
Andres Amin Uribe
andresamin@gmail.com
3102167356
![image](https://cloud.githubusercontent.com/assets/11579885/8321851/ebc6d99a-19f1-11e5-9598-786504aead4a.png)

**Comment by Lucia13** [comment]
Lucia Suárez
lucerolucia@gmail.com
314 256 8098

**Comment by fannytg** [comment]
Fanny Angélica Torrado G
fannytg@gmail.com
3168234454

**Comment by ingjuanocampo** [comment]
Nombre: Juan Manuel Ocampo 
Cel: 313 755 0993 
Mail: ing.juanocampo@gmail.com

**Comment by vitorresr** [comment]
Nombre: Viviana Paola Torres
Cel: 304 5 47 54 74
Mail: vpaolillatr@gmail.com

**Comment by cmauroie** [comment]
Mauricio Idárraga
3122611700
ing-mauricio@outlook.com

**Comment by LinaSep** [comment]
Lina Sepúlveda
Cel: 312 374 93 71
Email: linasep@lysepdesigner.com / linisysp@hotmail.com
Linkedin: https://co.linkedin.com/pub/lina-sep%C3%BAlveda/21/923/8b6

**Comment by Maru27** [comment]
María Eugenia Pachón Mayorga
3209459424
marupachon@hotmail.com

**Comment by alejo8591** [comment]
multinacional brasilera solicita desarrolladores Java con experiencia, pago todo por nómina, interesados enviar HV a obernal@stefanini.com URGENTE

**Comment by 9ggomez** [comment]
Gustavo Gómez (Diseñador Gráfico)
3103359591
9ggomez@gmail.com

**Comment by ricarsant** [comment]
Ricardo Santacruz
3214291335
rjgarzon@hotmail.com
rjgarzon1@gmail.com

**Comment by aspalenciap** [comment]
Armando Palencia
aspalenciap@unal.edu.co
3112954310
