### ISSUE TITLE
Videos Youtube sobre Nodejs y enlace a código fuente

### ISSUE THREAD

**Issue by desaextremo** [alejo8591/unipiloto-am-2#4]
<strong>Enlace a videos del canal:</strong> https://www.youtube.com/playlist?list=PLJEglAUdzLXIvSSK6oZwZ0VmZKSFYFgx0

<strong>Enlace a código en github:</strong> https://github.com/josemalive/NodejsReference

**Comment by alejo8591** [comment]
@desaextremo muchas gracias por compartir, la información fue publicada en la Wiki del repositorio
