### ISSUE TITLE
Enlaces de recursos sobre Nodejs del sitio : www.desarrolloweb.com

### ISSUE THREAD

**Issue by desaextremo** [alejo8591/unipiloto-am-2#5]
<strong>NodeJS es mucho más que Javascript del lado del servidor #programadorIO :</srong> https://www.youtube.com/watch?v=9kk1A5_IaQ0

<strong>Manual sobre Nodejs</strong> http://www.desarrolloweb.com/manuales/manual-nodejs.html

<strong>Arquitectura de la web con NodeJS #programadorIO:</strong> https://www.youtube.com/watch?v=M78gCRhqeUA

<strong>NodeJS require y NPM, Eventos y Streams #jsIO</strong> https://www.youtube.com/watch?v=nU4rUOleCfA

<strong>Introducción a nodeJS #nodeIO:</strong> https://www.youtube.com/watch?v=a7XOVa5rybg

**Comment by alejo8591** [comment]
@desaextremo información publicada, y muchas gracias por compartir. ¡Saludos!
