### ISSUE TITLE
Recursos de Genbetadev sobre NodeJS: www.genbetadev.com

### ISSUE THREAD

**Issue by desaextremo** [alejo8591/unipiloto-am-2#6]
<strong>¿Cómo funciona Node.js?</strong> http://www.genbetadev.com/frameworks/como-funciona-node-js

<strong>Introducción a la programación asíncrona con Node.js</strong> http://www.genbetadev.com/frameworks/introduccion-a-la-programacion-asincrona-con-nodejs

<strong>Node.js y npm</strong> http://www.genbetadev.com/frameworks/node-js-y-npm

<strong>Node.js</strong> http://www.genbetadev.com/productos/lenguajes-y-plataformas/nodejs

<strong>¿Node.js y JavaScript para hacer juegos?</strong> http://www.genbetadev.com/respuestas/node-js-y-javascript-para-hacer-juegos

<strong>ntroducción a la programación asíncrona con Node.js: Desarrollo web con express.js</strong> http://www.genbetadev.com/frameworks/introduccion-a-la-programacion-asincrona-con-nodejs-desarrollo-web-con-expressjs

**Comment by alejo8591** [comment]
@desaextremo Se publican los enlaces en la Wiki del repositorio oficial del Diplomado, muchas gracias por compartir. ¡Saludos!
