### ISSUE TITLE
Libros Node JS

### ISSUE THREAD

**Issue by desaextremo** [alejo8591/unipiloto-am-2#7]
<strong>Learning Node.js</strong> https://drive.google.com/file/d/0By20oENHm0_ZS3JLT0otQ2xlQ2c/view?usp=sharing

<strong>Node web development</strong>  https://drive.google.com/file/d/0By20oENHm0_ZeFNPZkVvTkR5aGM/view?usp=sharing

<strong>Node.js in Practice</strong> https://drive.google.com/file/d/0By20oENHm0_ZT2lJMEJGZ2N5MG8/view?usp=sharing

<strong>Node.js, MongoDB, and AngularJS Web Development</strong> https://drive.google.com/file/d/0By20oENHm0_ZLVl4TTJNbF9TTDA/view?usp=sharing

<strong>The Node Beginner Book</strong> https://drive.google.com/file/d/0By20oENHm0_ZaVQzSGRXb0JWNkk/view?usp=sharing

<strong>Web Development with Node and Express</strong>  https://drive.google.com/file/d/0By20oENHm0_ZTFdBNXRheWZZVkU/view?usp=sharing

**Comment by alejo8591** [comment]
@desaextremo gracias por el aporte de los libros. Los publicare en la Wiki del repositorio siempre y cuando tengan licencias que lo permitan hacer (Creative Commons, PDF Free), si son de pago no podría hacerlo.

**Comment by alejo8591** [comment]
No es posible publicar el libro **Learning Node.js** pues es un libro de pago y no tiene versión web de uso libre disponible: http://ow.ly/M9fme

**Comment by alejo8591** [comment]
No es posible publicar el libro **Node web development** Pues es un libro de pago y no tiene versión web de uso libre disponible: http://ow.ly/MbGwa

**Comment by alejo8591** [comment]
No es posible publicar el libro **Node.js in Practice** Pues es un libro de pago y no tiene versión web de uso libre disponible: http://ow.ly/MbHdo

**Comment by alejo8591** [comment]
No es posible publicar el libro **Node.js, MongoDB, and AngularJS Web Development** Pues es un libro de pago y no tiene versión web de uso libre disponible: http://ow.ly/MbHGi

**Comment by alejo8591** [comment]
No es posible publicar el libro **The Node Beginner Book** Pues es un libro de pago, pero si tiene un tutorial o guia en el sitio oficial este es el que publicare: http://ow.ly/MbHXV

**Comment by alejo8591** [comment]
No es posible publicar el libro **Web Development with Node and Express** pues es un libro de pago y no tiene versión web de uso libre disponible: http://ow.ly/MbIjq

**Comment by alejo8591** [comment]
@desaextremo voy a cerrar el issues pues ya esta resuelta la duda con respecto a los libros. Sólo publicare **The Node Beginner Book** pero el sitio oficial que hay una información muy interesante. Agradezco mucho que sigas compartiendo material, saludos...!!
