### ISSUE TITLE
Comparativo de Licencias

### ISSUE THREAD

**Issue by andresDesigner** [alejo8591/unipiloto-am-2#9]
Buenos dias,

Retomando el tema de clase sobre los tipos de licencia, lo encontré en wikipedia, sin embargo no se si la información es totalmente válida.

http://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

**Comment by alejo8591** [comment]
@andresDesigner muchas gracias por el aporte lo estaré publicando en la Wiki del repositorio oficial del Diplomado (AM-2). ¡Saludos!
